-- structure inspiration taken from:
-- https://github.com/LunarVim/Launch.nvim/

require("core.spec")

require("core.aucmds")
require("core.settings")
require("core.keymaps")

plugin("plugins.luarocks")
plugin("plugins.colorscheme")
plugin("plugins.telescope")
plugin("plugins.treesitter")
plugin("plugins.surround")
plugin("plugins.kommentary")
plugin("plugins.luasnip")
plugin("plugins.cmp")
plugin("plugins.bufferline")
plugin("plugins.md-table")
plugin("plugins.neorg")
plugin("plugins.fidget")
plugin("plugins.colorizer")
plugin("plugins.gitsigns_plugin")
plugin("plugins.mason")
plugin("plugins.conform")
plugin("plugins.lualine")
plugin("plugins.gen-nvim")
plugin("plugins.plant-uml-syntax")
plugin("plugins.prisma")
plugin("plugins.autopairs")
plugin("plugins.vimtex")
plugin("plugins.oil")
plugin("plugins.jupynium")
plugin("plugins.whichkey")
plugin("plugins.todo_comments")
plugin("plugins.zen-mode")
plugin("plugins.whitespaces")
plugin("plugins.dooing")
plugin("plugins.lazydev")
plugin("plugins.bigfile")
plugin("plugins.r-nvim")
plugin("plugins.cmp_r")

require("plugins.lazy")
