local plug = require("core.plug")
local plugin = plug.plugin

require("core.aucmds")
require("core.settings")
require("core.keymaps")

plugin("plugins.colorscheme")

plugin("plugins.autopairs")
plugin("plugins.bufferline")
plugin("plugins.cmp")
plugin("plugins.colorizer")
plugin("plugins.conform")
plugin("plugins.dap")
plugin("plugins.flash")
plugin("plugins.gitsigns_plugin")
plugin("plugins.java-nvim")
plugin("plugins.lazydev")
plugin("plugins.lualine")
plugin("plugins.luasnip")
plugin("plugins.mason")
plugin("plugins.oil")
plugin("plugins.snacks")
plugin("plugins.surround")
plugin("plugins.todo_comments")
plugin("plugins.arborist")
plugin("plugins.vimtex")
plugin("plugins.whichkey")
plugin("plugins.whitespaces")
plugin("plugins.wiki")
plugin("plugins.present")

vim.cmd([[packadd nvim.undotree]])
vim.cmd([[packadd nvim.difftool]])

plug.load()
