theme = "space-villain"
icons = "awesome5"

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time} {power}W"

[[block]]
block = "networkmanager"
on_click = "nm-connection-editor"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = false
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
