theme = "gruvbox-dark"
icons = "none"

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time} {power}W"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

# [[block]]
# block = "nvidia_gpu"
# label = ""
# show_memory = false
# interval = 1

# [[block]]
# block = "btc"
# interval = 10
# currency = "EUR"
# currency_list = ["EUR", "USD", "RUB", "AUD", "BRL", "CAD"]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
