[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "battery"
interval = 30
format = "$icon $percentage.bar(width:8, max_value:8) ($percentage.eng(w:2))"
full_format = "$icon $percentage.bar(width:8, max_value:8) (FULL)"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M) ($mem_total_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
format = "$icon $volume.bar(w:8) ($volume.eng(w:2))"

[[block]]
block = "time"
interval = 30
format = " $icon $timestamp.datetime(f:'%a %d/%m %R')"
