[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = "$icon $title - $artist [$prev $play $next]"
interface_name_exclude = ["firefox*"]

[[block]]
block = "battery"
interval = 30
format = "$icon ($percentage.eng(w:2))"
full_format = "$icon (FULL)"
empty_format = "$icon (EMPTY)"
not_charging_format = "$icon ~($percentage.eng(w:2))"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M) ($mem_used_percents.eng(w:2)) "

# [[block]]
# block = "speedtest"
# interval = 300
# format = "^icon_net_down $speed_down ^icon_net_up $speed_up"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
format = "$icon $volume.eng(w:2)"

[[block]]
block = "backlight"

@@ terminator
device = "acpi_video0"
@!

@@ legionnaire
device = "intel_backlight"
@!
minimum = 1
cycle = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
format = "$icon $brightness"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %R:%S')"
