#!/usr/bin/env bash

m_help() {
  echo "setup monitors on xorg"
  echo "options:"
  printf "\t-d\tdisconnect monitors\n"
  printf "\t-c\tconnect monitors\n"
}
connected_displays=`xrandr | grep -w "connected" | awk '{ print $1 }'`

case "$1" in
    -c)
	for each in $connected_displays; do
	    case "$each" in
		eDP*)
		    xrandr --output "$each" --off;
		    ;;
		HDMI-*)
		    xrandr --output "$each" --mode 1920x1080 --primary;
		    hdmi="$each"
		    ;;
		DP-*)
		    xrandr --output "$each" --mode 1920x1080 --right-of "$hdmi";
		    ;;
	    esac
	done
	;;
    -d)
	for each in $connected_displays; do
	    case "$each" in
		eDP*)
		    xrandr --output "$each" --mode 1920x1080 --primary;
		    ;;
		HDMI-*|DP-*)
		    xrandr --output "$each" --off
		    ;;
	    esac
	done
esac
