#!/usr/bin/env bash

m_help() {
  echo "setup monitors on xorg"
  echo "options:"
  printf "\t-d\tdisconnect monitors\n"
  printf "\t-c\tconnect monitors\n"
}

if test "$1" == "-c" && xrandr | grep "HDMI-1 connected" && xrandr | grep "DP-1 connected"; then
    xrandr --output eDP-1 --off;
    xrandr --output HDMI-1 --mode 1920x1080 --primary;
    xrandr --output DP-1 --mode 1920x1080 --right-of HDMI-1;
  elif [ "$1" == "-d" ]; then
    xrandr --output eDP-1 --mode 1920x1080 --primary;
    xrandr --output DP-1 --off
    xrandr --output HDMI-1 --off
  else
    m_help
fi
