#!/usr/bin/env python

import os
import time
import multiprocessing

import argparse

def parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser("timer",
                                     description="timer app which sends desktop notifications",
                                     add_help=True)
    parser.add_argument("-H", "--hours", type=int, help="Number of hours.")
    parser.add_argument("-m", "--minutes", type=int, help="Number of minutes.")
    parser.add_argument("-s", "--seconds", type=int, help="Number of seconds.")
    parser.add_argument("-M", "--message", help="Message to show when the timer is done.", default="Time is up!")
    return parser


def run(secs: int, msg: str) -> None:
    if os.fork() != 0:
        return
    time.sleep(secs)
    os.system(f"notify-send \"{msg}\"")


def main() -> None:
    secs = 0
    args = parser().parse_args()
    if args.seconds is not None:
        secs += args.seconds
    if args.minutes is not None:
        secs += args.minutes * 60
    if args.hours is not None:
        secs += args.hours * 60 * 60
    p = multiprocessing.Process(target=run, args=[secs, args.message])
    p.daemon = True
    p.start()
    p.join()


if __name__ == "__main__":
    main()
