# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

plugins=(vi-mode zsh-interactive-cd )

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/zir/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# enable starship
eval "$(starship init zsh)"

# alisases
alias ls='exa'
alias vi='nvim'
alias nssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias sus='sudo systemctl start suspend.target && i3lock -c 111111'
alias mute='pactl set-sink-volume 0 0%'
alias grep='rg'
alias ff='find -type f ! -name ".*" ! -path "*/.*" | fzf'
alias cswp='rm ~/.local/state/nvim/swap/* && rm ~/.local/state/nvim/log'
alias g='git'
alias dots='cd ~/clones/dotfiles/ && vi . && der2 -avRs && cd -'
alias wiki='(cd ~/wiki/ && nvim +"WikiIndex")'
alias yank='xsel -ib'
alias past='xsel -ob'
alias cdf='res=$(fd . ~ -t d | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden); if [ -n "$res" ]; then cd "$res"; fi'
alias sshadd='ssh-add ~/.ssh/id_ed25519-2024'

alias todo='vi ~/todo/todo.txt'
alias lg='lazygit'


## Tmux aliases
alias splith='tmux splitw -h -p 50'
alias splitv='tmux splitw -v -p 50'

if [[ ! "$(tty)" = "/dev/tty1" ]]; then
    if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
      tmux attach-session -t default || tmux new-session -s default
    fi
fi

bindkey -M viins 'jk' vi-cmd-mode
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
