add_newline = false
format = "$git_branch$git_status$lua$rust$c$cmake$java $directory$character"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold yellow"

[character]
success_symbol = "[→](bold cyan)" 
error_symbol = "[✗](bold red)"

[git_branch]
format = " [$symbol$branch]($style)"
style = "bold purple"

[git_status]
format = '([ \[$all_status$ahead_behind\]]($style))'
style = "bold red"
ahead = ""
behind = ""

[c]
format = ' [$symbol($version)]($style)'
symbol = "\ue61e "
version_format = "${major}.${minor}"
style = "bold cyan"

[cmake]
format = " via [CMake]($style)"

[java]
format = " [$symbol ($version)]($style)"
symbol = "\ue738"
version_format = "${major}.${minor}"
style = "bold cyan"

[rust]
format = ' rust [$version]($style)'
style = "bold cyan"

[lua]
format = ' lua [$version]($style)'
style = "bold cyan"
