add_newline = false
format = "$git_branch$git_status$lua$rust $directory$character"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold yellow"

[character]
success_symbol = "[→](bold cyan)" 
error_symbol = "[✗](bold red)"

[git_branch]
format = " [$symbol$branch]($style)"
style = "bold purple"

[git_status]
format = '([ \[$all_status$ahead_behind\]]($style))'
style = "bold red"

[rust]
format = ' rust [$version]($style)'
style = "bold cyan"

[lua]
format = ' lua [$version]($style)'
style = "bold cyan"
